global:
  resolve_timeout: 1m

route:
  receiver: alert-test

receivers:
 - name: alert-test
   slack_configs:
     - api_url: https://hooks.slack.com/services/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
    
