version: '3'
services:
   prometheus:
      image: prom/prometheus
      volumes:
         - ./prometheus.yml:/etc/prometheus/prometheus.yml
         - ./rules.yml:/etc/prometheus/rules.yml
      ports:
         - "9090:9090"
      restart: always
      environment:
        TZ: Asia/Tokyo

   snmpexporter:
      image: prom/snmp-exporter
      ports:
         - "9116:9116"  
      volumes:
         - ./snmp_exporter/generator/out/snmp.yml:/etc/snmp_exporter/snmp.yml
      restart: always
      environment:
        TZ: Asia/Tokyo
   
   alertmanager:
      image: prom/alertmanager
      volumes:
         - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
      ports:
         - "9093:9093"
      restart: always
      environment:
        TZ: Asia/Tokyo

   blackbox_exporter:
      image: prome/blackbox-exporter
      volumes:
        - ./blackbox_exporter/config.yml:/etc/blackbox_exporter/config.yml

   grafana:
      image: grafana/grafana
      ports:
         - 3000:3000
      volumes:
      - grafana:/var/lib/grafana
      restart: always
      environment:
        TZ: Asia/Tokyo
volumes:
   grafana:
     driver: local
    
