# my global config
global:
  scrape_interval:     10s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).
  external_labels:
    region: wide-camp
    env: hotstage

rule_files:
  - rules.yml
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 172.16.1.117:9093

scrape_configs:
  - job_name: blackbox_icmp
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
        - 172.16.1.20
        - 172.16.1.1
        - 172.16.1.2
        - 172.16.1.3
        - 172.16.1.5
        - 172.16.1.6
        - 172.16.1.7
        - 172.16.1.11
        - 172.16.1.12
        - 172.16.1.13
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.16.1.117:9115

  - job_name: prometheus
    static_configs:
      - targets: ['172.16.1.117:9090']
    relabel_configs:
     - source_labels: [job]
       target_label: job     
     - regex: __scheme__
       replacement: '${1}'
       action: labelmap

  - job_name: 'sw-noc-cisco'
    static_configs:
      - labels:
          type: sw-noc-cisco
        targets:
          - '172.16.1.6'
    metrics_path: /snmp
    params:
      module: [cisco]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.16.1.117:9116 

  - job_name: 'AP-Controller'
    static_configs:
      - labels:
          type: AP
        targets:
          - '172.16.1.20'
    metrics_path: /snmp
    params:
      module: [aruba]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.16.1.117:9116 
