{
 "title": "Aruba",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "apname", "query": "aiAPName" }
  ]
 },
 "panels": [
  {
   "title": "OperatingSyatem",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(aiClientOperatingSystem{aiClientOperatingSystem=\"OS X\"})",
     "legendFormat": "OS X"
    },
    {
     "expr": "count(aiClientOperatingSystem{aiClientOperatingSystem=\"Windows\"})",
     "legendFormat": "Windows"
    },
    {
     "expr": "count(aiClientOperatingSystem{aiClientOperatingSystem=\"iPhone\"})",
     "legendFormat": "iPhone"
    }
   ]
  },
  {
   "title": "Access User",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count(aiClientAPMac{aiClientAPMac=~\"$apname\"})"
    }
   ]
  },
  {
   "title": "ArubaAP CPU Utilization (%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aiAPCPUUtilization{aiAPMACAddress=~\"$apname\"}"
    }
   ]
  },
  {
   "title": "ArubaAP Memory Utilization (%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(aiAPTotalMemory{aiAPMACAddress=~\"$apname\"} - aiAPMemoryFree{aiAPMACAddress=~\"$apname\"}) / aiAPTotalMemory{aiAPMACAddress=~\"$apname\"} * 100"
    }
   ]
  },
  {
   "title": "TxDataByete",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aiRadioTxDataBytes / 1000" }
   ]
  }
 ]
}