{
 "title": "Monitoring",
 "description": "For snmp exporter with dot1dStpPortState",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "STPport", "query": "dot1dStpPortState" },
   {
    "name": "Interface",
    "query": "query_result(ifInOctets{job=\"snmp-exporter\"})"
   },
   {
    "name": "Internal_Interface",
    "query": "query_result(ifInOctets{job=\"snmp-exporter\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "Time",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ReachabilityLossAlet",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=ReachabilityLoss",
     "labelSelector": "*",
     "legendFormat": "{{msg}}",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "InstanceDownAlert",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "alertname=InstanceDown",
     "labelSelector": "*",
     "legendFormat": "{{msg}}",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "ReachabilityLossAlert",
   "type": "table",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "alertname=ReachabilityLoss",
     "labelSelector": "*",
     "legendFormat": "{{msg}}",
     "target": "Query",
     "type": "table"
    }
   ]
  },
  {
   "title": "Ping Check",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "targets": [
    { "expr": "probe_success", "legendFormat": "{{purpose}}" }
   ]
  }
 ]
}